# Use postgres/example user/password credentials
version: '3.1'

services:
  tuum-application:
    image: openjdk:11
    container_name: tuum-application
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    command: ['java', '-jar', '-Dspring.profiles.active=docker', '/usr/app/build/libs/tuum-0.0.1-SNAPSHOT.jar']
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - rabbitmq_go_net

  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/main/resources/_dbinit:/docker-entrypoint-initdb.d/:ro
    container_name: tuum_db
    ports:
      # Bind host port 5431 to PostgreSQL port 5432
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      LANG: et_EE.utf8
    networks:
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-rabbit/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
